carros/urls.py
from django.urls import path
from . import views

app_name='carros'
urlpatterns = [
    path('', views.carros, name='listar'),
    path('cadastrar/', views.carroCriar, name='criar'),
    path('editar/<slug:slugCarro>/', views.CarroEditar.as_view(), name='editar'),
    path('excluir/<slug:slugCarro>/', views.CarroExcluir.as_view(), name='excluir'),
]

urlpatterns += [
    path('<slug:slugCarro>/versao/cadastrar/',views.versaoCriar, name='versaoCriar'),
    path('<slug:slugCarro>', views.versoes, name='versoes'),
    path('<slug:slugCarro>/versao/<int:pk>/detalhe', views.VersaoDetalheView.as_view(), name='versaoDetalhe'),
    path('<slug:slugCarro>/versao/<int:pk>/editar', views.VersaoEditar.as_view(), name='versaoEditar'),
    path('<slug:slugCarro>/versao/<int:pk>/excluir', views.VersaoExcluir.as_view(), name='versaoExcluir'),
]

clientes/urls.py
from django.urls import path
from . import views


app_name = 'clientes'
urlpatterns = [
    path('', views.ClienteListar.as_view(), name='listar'),
    path('cadastrar/', views.ClienteCriar.as_view(), name='criar'),
    path('editar/<int:pk>', views.ClienteEditar.as_view(), name='editar'),
    path('excluir/<int:pk>', views.ClienteExcluir.as_view(), name='excluir'),
    path('<int:pk>/detalhe', views.ClienteDetalhe.as_view(), name='detalhe'),
]

django_concessionaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='inicio'),
    path('pessoas/', include('pessoas.urls')),
    path('carros/', include('carros.urls')),
    path('clientes/', include('clientes.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
]

urlpatterns += [
    path('contas/', include('django.contrib.auth.urls')),
    path('contas/login/', views.LoginView.as_view(), name='login'),
    path('contas/logout/', views.LogoutView.as_view(), name='logout'),
    path('contas/senha_redefinir/', views.PasswordResetView.as_view(), name='password_reset'),
    path('contas/senha_redifinir/solicitado', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('contas/redefinir/uidb64/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('contas/redefinir/sucesso', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'permissoes.redirecionar.handler403'

carros/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import date

anoAtual = date.today().year

class Seguranca(models.Model):
    item = models.CharField(max_length=50)

    def __str__(self):
        return self.item
    
class Combustivel(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return self.tipo
    
    class Meta:
        verbose_name_plural = 'Combustiveis'
    
class Acessorio(models.Model):
    item = models.CharField(max_length=50)

    def __str__(self):
        return self.item
    
class Motor(models.Model):
    nome = models.CharField(max_length=50)
    cv = models.IntegerField()
    torque = models.FloatField()
    rpm = models.IntegerField()
    valvulas = models.IntegerField()
    cilindros = models.IntegerField(default=3)

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = 'Motores'

class Direcao(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return self.tipo
    
    class Meta:
        verbose_name_plural = 'Direcoes'

class Carro(models.Model):
    nome = models.CharField(max_length=30, unique=True)
    slugCarro = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.slugCarro:
            self.slugCarro = slugify(self.nome)
        return super().save(*args, **kwargs)
    
    class Meta:
        permissions = (
            ('permissao_gerente', 'permissao gerente'),
            ('permissao_supervisor', 'permissao supervisor'),
            ('permissao_vendedor', 'permissao vendedor'),
            ('permissao_funcionario', 'permissao todos funcionarios'),
        )
    
class Versao(models.Model):
    carro = models.ForeignKey(Carro, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=50, unique=True)
    motor = models.ForeignKey(Motor, on_delete=models.DO_NOTHING)
    combustivel = models.ForeignKey(Combustivel, on_delete=models.DO_NOTHING)
    direcao = models.ForeignKey(Direcao, on_delete=models.DO_NOTHING)
    seguranca = models.ManyToManyField(Seguranca, related_name="versao_seguranca", blank=True)
    acessorio = models.ManyToManyField(Acessorio, related_name="versao_acessorio", blank=True)
    imagem = models.ImageField(upload_to='carros', blank=True, null=True)
    ano = models.IntegerField(default=anoAtual)
    modelo = models.IntegerField(default=anoAtual)
    estoque = models.IntegerField(default=0) 
    slugVersao = models.SlugField(unique=True, null=True, blank=True)

    class Meta:
        permissions = (
            ('permissao_gerente', 'permissao gerente'),
            ('permissao_supervisor', 'permissao supervisor'),
            ('permissao_vendedor', 'permissao vendedor'),
            ('permissao_funcionario', 'permissao todos funcionarios'),
        )

    def __str__(self):
        return self.nome
    
    def save(self, *args, **kwargs):
        if not self.slugVersao:
            self.slugVersao = slugify(self.nome)
        return super().save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Versoes'
    
    

carros/forms.py
from django import forms
from .models import Versao

class VersaoModelForm(forms.ModelForm):
    
    class Meta:
        model = Versao
        fields = "__all__"
        exclude = ['estoque','slugVersao']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields[field].widget.attrs.update({'placeholder':field})
            self.fields[field].widget.attrs.update({'style': 'margin-bottom:17px;'})
            self.fields['nome'].widget.attrs.update({'placeholder':'nome da nova versao'})

carros/views.py
from .models import Carro, Versao, Seguranca, Direcao, Motor, Combustivel, Acessorio
from django.contrib import messages
from django.contrib.messages import constants
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from carros.forms import VersaoModelForm
from permissoes.redirecionar import RedirectPermissionRequiredMixin


@login_required(login_url=reverse_lazy('login'))
def carros(request):
    carros = Carro.objects.all()
    todasVersoes = Versao.objects.all()
    todasImagens = ""
    for todas in todasVersoes:
        todasImagens += todas.imagem.url + ","
    
    context = {
        'carros':carros,
        'todasImagens':todasImagens,
    }
    return render(request, 'carros/carros.html', context=context)


@login_required(login_url=reverse_lazy('login'))
@permission_required('carros.permissao_supervisor', raise_exception=True)
def carroCriar(request):
    if request.method == "GET":
        return render(request, 'carros/carroCriar.html')
    elif request.method == "POST":
        nome = request.POST.get("nome")
        carro = Carro ( nome= nome,)
        carro.save()
        messages.add_message(request, constants.SUCCESS, f'carro {nome} cadastrado com sucesso')
        messages.add_message(request, constants.INFO, 'cadastre agora uma versão:')
        slugCarro = carro.slugCarro
        return redirect(reverse('carros:versaoCriar', kwargs={'slugCarro':slugCarro}))
        
class CarroEditar(RedirectPermissionRequiredMixin, UpdateView):
    model = Carro
    fields = ['nome']
    template_name = 'carros/carroEditar.html'
    permission_required = 'carros.permissao_supervisor'
    # raise_exception = True
    
    success_url = reverse_lazy('carros:listar')

    def get_object(self, queryset=None):
        slug_field = 'slugCarro'
        slug = self.kwargs.get(slug_field)
        queryset = self.get_queryset()
        obj = queryset.get(**{slug_field: slug})
        return obj

class CarroExcluir(RedirectPermissionRequiredMixin, DeleteView):
    model = Carro
    template_name = 'carros/carroExcluir.html'
    permission_required = 'carros.permissao_gerente'
    success_url = reverse_lazy('carros:listar')

    def get_object(self, queryset=None):
        slug_field = 'slugCarro'
        slug = self.kwargs.get(slug_field)
        queryset = self.get_queryset()
        obj = queryset.get(**{slug_field: slug})
        return obj

    def form_valid(self, form):
            self.object = self.get_object()
            if Versao.objects.filter(carro=self.object).exists():
                messages.error(self.request,'este carro já tem versão cadastrada!' )
                return redirect(reverse('carros:versoes', kwargs={'slugCarro':self.object.slugCarro}))
            messages.success(self.request, f'carro {self.object.nome} excluido com sucesso')
            return super().form_valid(form)

@login_required(login_url=reverse_lazy('login'))
def versoes(request, slugCarro):
    carroSelecionado = Carro.objects.get(slugCarro=slugCarro)
    versoes = Versao.objects.filter(carro__id=carroSelecionado.id)

    context = {
        'versoes':versoes,
        'carroSelecionado':carroSelecionado,
    }
    return render(request, 'carros/carroVersoes.html', context=context)


class VersaoDetalheView(RedirectPermissionRequiredMixin, generic.DetailView):
    model = Versao
    template_name='carros/versaoDetalhe.html'
    permission_required = 'carros.permissao_funcionario'

@login_required(login_url=reverse_lazy('login'))
@permission_required('carros.permissao_supervisor', raise_exception=True)
def versaoCriar(request, slugCarro):
    carro = Carro.objects.get(slugCarro=slugCarro)
    if request.method == "GET":
        form = VersaoModelForm()
        context = {
            'carro':carro,
            'form':form
        }
        return render(request, 'carros/versaoCriar.html', context=context)
    elif request.method == "POST":
        form = VersaoModelForm(request.POST, request.FILES)

    if form.is_valid():
        form.save()
        messages.add_message(request, constants.SUCCESS, 'versão cadastrada com sucesso.')
    else:
        messages.add_message(request, constants.ERROR, form.errors)
        context = {
            'carro':carro,
            'form':form,
        }
        return render(request, 'carros/versaoCriar.html', context=context)

    slugCarro = carro.slugCarro
    return redirect(reverse('carros:versoes', kwargs={'slugCarro':slugCarro}))


class VersaoEditar(RedirectPermissionRequiredMixin, UpdateView):
    model = Versao
    fields = ['nome','motor','combustivel','direcao','seguranca','acessorio','imagem','ano','modelo']
    template_name = 'carros/versaoEditar.html'
    permission_required = 'carros.permissao_supervisor'
    # success_url = reverse_lazy('carros:listar')

    def get_success_url(self):
        versao_id = self.kwargs['pk']
        versao = Versao.objects.get(id=versao_id)
        carro = versao.carro
        slugCarro = carro.slugCarro
        return reverse_lazy ('carros:versaoDetalhe', kwargs={'slugCarro':slugCarro, 'pk':versao_id})
    
    def form_valid(self,form):
        messages.success(self.request, 'versao alterada com sucesso')
        return super().form_valid(form)

class VersaoExcluir(RedirectPermissionRequiredMixin, DeleteView):
    model = Versao
    template_name = 'carros/versaoExcluir.html'
    success_url = reverse_lazy('carros:versoes', kwargs={'slugCarro':'teste'})
    permission_required = 'carros.permissao_supervisor'

carros/templates/carros/cadastrar_versao.html
{% extends 'base.html' %}

{% block 'body' %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        
        <form action="{% url 'carros:cadastrar_versao' carro.slugCarro %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                
                <div class="col-md-5">
                        {{form.nome.label_tag}}
                        {{form.nome}}
                        {{form.nome.placeholder}}
                        
                        {{form.motor.label_tag}}
                        {{form.motor}}
                        
                        {{form.seguranca.label_tag}}
                        {{form.seguranca}}
                        
                        {{form.ano.label_tag}}
                        {{form.ano}}
                        
                        {{form.imagem.label_tag}}
                        {{form.imagem}}
                </div>
                
                <div class="col-md-5">
                        {{form.combustivel.label_tag}}
                        {{form.combustivel}}
                        
                        {{form.direcao.label_tag}}
                        {{form.direcao}}
                        
                        {{form.acessorio.label_tag}}
                        {{form.acessorio}}
                        
                        {{form.modelo.label_tag}}
                        {{form.modelo}}

                        <input type="hidden" name="carro" value="{{carro.id}}">

                        <input class="btn btn-success" type="submit" value="Cadastrar Versão" style="margin-top: 31px;" >
                </div>
            </div>
            
        </form>

    </div>

{% endblock %}

carros/templates/carros/carroCriar.html
{% extends 'base.html' %}

{% block 'body' %}

    <div class="container" >
        <div class="row">
            <div class="col-md-2.5">
                <form action="{% url 'carros:criar' %}" method="POST">{% csrf_token %}
                    <input type="text" class="form-control" name="nome" placeholder="Nome do novo carro" style="margin-bottom: 10px;">
                    <input type="submit" class="btn btn-success" value="Cadastrar">
                    <a href="javascript:history.back()" class="btn btn-secondary botao">Voltar</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

carros/templates/carros/carroEditar.html
{% extends 'base.html' %}

{% block 'body' %}

    <div class="container" >
        <form action="{% url 'carros:editar' carro.slugCarro %}" method="POST"> {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-success" value="salvar alterações">
        </form>
    </div>

{% endblock %}

carros/templates/carros/carroExcluir.html
{% extends 'base.html' %}

{% block 'body' %}
    <h3>Confirma a exclusão do carro {{object}}?</h3>
    <form action="" method="POST"> {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Excluir">
        <a href="{% url 'carros:listar' %}" class="btn btn-secondary">Voltar</a>
    </form>
{% endblock %}

carros/templates/carros/carroVersoes.html
{% extends 'base.html' %}

{% block 'body' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a href=" {% url 'carros:editar' carroSelecionado.slugCarro %}" class="btn btn-secondary botao">Editar</a>
                    <a href=" {% url 'carros:excluir' carroSelecionado.slugCarro %}" class="btn btn-danger botao">Excluir</a>
                    <a href=" {% url 'carros:versaoCriar' carroSelecionado.slugCarro %}" class="btn btn-primary botao">Nova Versao</a>
                    <table class="table table-dark">
                        <thead>
                            <tr>
                                <th scope="col" class="headLista">{{ carroSelecionado.nome }}</th>
                            </tr>
                        </thead>
                        {% if versoes.exists %}

                            <tbody>
                                {% for versao in versoes %}
                                    <tr>
                                        <th><a href=" {% url 'carros:versaoDetalhe' carroSelecionado.slugCarro versao.id %}">{{ versao.nome }}</a></th>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        {% else %}
                            <thead>
                                <tr>
                                    <th scope="col">Não há versões cadastradas</th>
                                </tr>
                            </thead>
                        {% endif %}
                    </table>                    
                </div>
                <div class="col-md-9">
                    <div class="listar_versoes">
                        <div class="row"> 
                        {% for versao in versoes %}
                            <div class="col-md-4">
                                <div style="background-color: #0f0f0f; width: 18rem;" class="card" style="width: 18rem;">
                                    <img width="100%" class="card-img-top" src="{{versao.imagem.url}}">
                                    <div class="card-body">
                                        <h5 class="card-title">{{versao.nome}}</h5>
                                        <a href="{% url 'carros:versaoDetalhe' carroSelecionado.slugCarro versao.id %}" class="btn btn-primary">Detalhes</a>
                                    </div>
                                </div>
                                <br>
                            </div>
                        {% endfor %}
                        </div> 
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

carros/templates/carros/carros.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="container">
        <div class="row">
            <div class="col-md-3 add-scroll">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <a href="{% url 'carros:criar' %}" class="btn btn-primary botao">Novo carro</a>
                            <th scope="col" class="headLista">Carros cadastrados:</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for carro in carros %}
                            <tr>
                                <th><a href=" {% url 'carros:versoes' carro.slugCarro %}">{{ carro.nome }} </a></th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-9">
                <div style="width: 43rem;" class="card" style="width: 43rem;">
                    <img id="imagem" width="250px%" height="450px" class="card-img-top" src="">
                </div>
                <br>
            </div>
        </div>
    </div>
    <input type="hidden" id="todasImagens" value="{{todasImagens}}">
    <script src="{% static 'js/exibirImagens.js' %}"></script>
{% endblock %}

carros/templates/carros/carrosVersoes.html
{% extends 'base.html' %}

{% block 'body' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a href=" {% url 'carros:editar' carroSelecionado.slugCarro %}" class="btn btn-secondary botao">Editar</a>
                    <a href=" {% url 'carros:excluir' carroSelecionado.slugCarro %}" class="btn btn-danger botao">Excluir</a>
                    <a href=" {% url 'carros:versaoCriar' carroSelecionado.slugCarro %}" class="btn btn-primary botao">Nova Versao</a>
                    <table class="table table-dark">
                        <thead>
                            <tr>
                                <th scope="col" class="head-listas">{{ carroSelecionado.nome }} {{slugCarro}}</th>
                            </tr>
                        </thead>
                        {% if versoes.exists %}

                            <tbody>
                                {% for versao in versoes %}
                                    <tr>
                                        <th><a href=" {% url 'carros:versaoDetalhe' carroSelecionado.slugCarro versao.id %}">{{ versao.nome }}:</a></th>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        {% else %}
                            <thead>
                                <tr>
                                    <th scope="col">Não há versões cadastradas</th>
                                </tr>
                            </thead>
                        {% endif %}
                    </table>                    
                </div>
                <div class="col-md-9">
                    <div class="listar_versoes">
                        <div class="row"> 
                        {% for versao in versoes %}
                            <div class="col-md-4">
                                <div style="background-color: #0f0f0f; width: 18rem;" class="card" style="width: 18rem;">
                                    <img width="100%" class="card-img-top" src="{{versao.imagem.url}}">
                                    <div class="card-body">
                                        <h5 class="card-title">{{versao.nome}}</h5>
                                        <a href="{% url 'carros:versaoDetalhe' carroSelecionado.slugCarro versao.id %}" class="btn btn-primary">Detalhes</a>
                                    </div>
                                </div>
                                <br>
                            </div>
                        {% endfor %}
                        </div> 
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

carros/templates/carros/carros_criar.html
{% extends 'base.html' %}

{% block 'body' %}

    <div class="container" >
        <div class="row">
            <div class="col-md-3">
                <form action="{% url 'carros:cadastrar' %}" method="POST">{% csrf_token %}
                    <input type="text" class="form-control" name="nome" placeholder="Nome do novo carro" style="margin-bottom: 10px;">
                    <input type="submit" class="btn btn-success" value="Cadastrar carro">
                    <a href="{% url 'carros:listar' %}" class="btn btn-danger">Cancelar</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

carros/templates/carros/carros_versoes.html
{% extends 'base.html' %}

{% block 'body' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a href=" {% url 'carros:cadastrar_versao' carroSelecionado.slugCarro %}" class="botao">Nova Versao</a>
                    <table class="table table-dark">
                        <thead>
                            <tr>
                                <th scope="col" class="head-listas">{{ carroSelecionado.nome }}</th>
                            </tr>
                        </thead>
                        {% if versoes.exists %}

                            <tbody>
                                {% for versao in versoes %}
                                    <tr>
                                        <th><a href=" {% url 'carros:detalhe' carroSelecionado.slugCarro versao.id %}">{{ versao.nome }}:</a></th>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        {% else %}
                            <thead>
                                <tr>
                                    <th scope="col">Não há versões cadastradas</th>
                                </tr>
                            </thead>
                        {% endif %}
                    </table>                    
                </div>
                <div class="col-md-9">
                    <div class="listar_versoes">
                        <div class="row"> 
                        {% for versao in versoes %}
                            <div class="col-md-4">
                                <div style="background-color: #0f0f0f; width: 18rem;" class="card" style="width: 18rem;">
                                    <img width="100%" class="card-img-top" src="{{versao.imagem.url}}">
                                    <div class="card-body">
                                        <h5 class="card-title">{{versao.nome}}</h5>
                                        <a href="{% url 'carros:detalhe' carroSelecionado.slugCarro versao.id %}" class="btn btn-primary">Detalhes</a>
                                    </div>
                                </div>
                                <br>
                            </div>
                        {% endfor %}
                        </div> 
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

carros/templates/carros/versaoCriar.html
{% extends 'base.html' %}

{% block 'body' %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        
        <form action="{% url 'carros:versaoCriar' carro.slugCarro %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                
                <div class="col-md-5">
                        {{form.nome.label_tag}}
                        {{form.nome}}
                        {{form.nome.placeholder}}
                        
                        {{form.motor.label_tag}}
                        {{form.motor}}
                        
                        {{form.seguranca.label_tag}}
                        {{form.seguranca}}
                        
                        {{form.ano.label_tag}}
                        {{form.ano}}
                        
                        {{form.imagem.label_tag}}
                        {{form.imagem}}
                </div>
                
                <div class="col-md-5">
                        {{form.combustivel.label_tag}}
                        {{form.combustivel}}
                        
                        {{form.direcao.label_tag}}
                        {{form.direcao}}
                        
                        {{form.acessorio.label_tag}}
                        {{form.acessorio}}
                        
                        {{form.modelo.label_tag}}
                        {{form.modelo}}

                        <input type="hidden" name="carro" value="{{carro.id}}">

                        <input class="btn btn-success" type="submit" value="Cadastrar Versão" style="margin-top: 31px;" >
                </div>
            </div>
            
        </form>

    </div>

{% endblock %}

carros/templates/carros/versaoDetalhe.html
{% extends 'base.html' %}

{% block 'body' %}
    {{ block.super }}
    <div class="container">
        <a href="{%url 'carros:versaoEditar' versao.carro.slugCarro versao.pk %} " class="btn btn-primary botao">Editar</a>
        <a href="{%url 'carros:versaoExcluir' versao.carro.slugCarro versao.pk %} " class="btn btn-danger botao">Excluir</a>
        
        <div class="row">
            <div class="col-md-4">
                <h3>Versão: {{versao}}</h3>

                <p>Carro: {{versao.carro}}</p>
                <p>Combustivel: {{versao.combustivel}}</p>
                <h6>Itens de Seguranca:</h6>
                    <ul>
                        {% for item in versao.seguranca.all %}
                            <li>{{item}}</li>    
                        {% endfor %}
                    </ul>
                <h6>Acessorios:</h6>
                <ul>
                    {% for item in versao.acessorio.all %}
                        <li>{{item}}</li>    
                    {% endfor %}
                </ul>
                <p>Ano: {{versao.ano}}</p>
                <p>Modelo: {{versao.modelo}}</p>
                <p>Estoque: {{versao.estoque}}</p>
            </div>
            <div class="col-md-8">
                <div style="background-color: #0f0f0f; width: 50rem;">
                    <img width="100%" src="{{versao.imagem.url}}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

carros/templates/carros/versaoEditar.html
{% extends 'base.html' %}

{% block 'body' %}

    <div class="container" >
        <form action="" method="POST"> {% csrf_token %}
            <div class="colunasDuas">
                {{form.as_p}}
            </div>
            <input type="submit" class="btn btn-success" value="salvar alterações">
        </form>
    </div>

{% endblock %}

carros/templates/carros/versaoExcluir.html
{% extends 'base.html' %}

{% block 'body' %}
    <h3>Confirma a exclusão da versão {{object}}?</h3>
    <form action="" method="POST"> {% csrf_token %}
        <input type="submit" class="btn btn-danger botao" value="Excluir">
        <a href="javascript:history.back()" class="btn btn-secondary botao">Voltar</a>
    </form>
{% endblock %}