carros/urls.py
from django.urls import path
from . import views

app_name='carros'
urlpatterns = [
    path('', views.carros, name='listar'),
    path('cadastrar/', views.carroCriar, name='criar'),
    path('editar/<slug:slugCarro>/', views.CarroEditar.as_view(), name='editar'),
    path('excluir/<slug:slugCarro>/', views.CarroExcluir.as_view(), name='excluir'),
]

urlpatterns += [
    path('<slug:slugCarro>/versao/cadastrar/',views.versaoCriar, name='versaoCriar'),
    path('<slug:slugCarro>', views.versoes, name='versoes'),
    path('<slug:slugCarro>/versao/<int:pk>/detalhe', views.VersaoDetalheView.as_view(), name='versaoDetalhe'),
    path('<slug:slugCarro>/versao/<int:pk>/editar', views.VersaoEditar.as_view(), name='versaoEditar'),
    path('<slug:slugCarro>/versao/<int:pk>/excluir', views.VersaoExcluir.as_view(), name='versaoExcluir'),
]

django_concessionaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='inicio'),
    path('pessoas/', include('pessoas.urls')),
    path('carros/', include('carros.urls')),
    path('clientes/', include('clientes.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
]

urlpatterns += [
    path('contas/', include('django.contrib.auth.urls')),
    path('contas/login/', views.LoginView.as_view(), name='login'),
    path('contas/logout/', views.LogoutView.as_view(), name='logout'),
    path('contas/senha_redefinir/', views.PasswordResetView.as_view(), name='password_reset'),
    path('contas/senha_redifinir/solicitado', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('contas/redefinir/uidb64/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('contas/redefinir/sucesso', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'permissoes.redirecionar.handler403'

vendas/urls.py
from django.urls import path
from . import views


app_name = 'vendas'
urlpatterns = [
    path('', views.VendasListar.as_view(), name='listar'),
    path('cadastrar/', views.VendasCriar.as_view(), name='criar'),
    path('editar/<int:pk>', views.VendasEditar.as_view(), name='editar'),
    path('excluir/<int:pk>', views.VendasExcluir.as_view(), name='excluir'),
]

vendas/models.py
from django.db import models
from clientes.models import Cliente
from colaboradores.models import Colaborador
from carros.models import Versao

class Venda(models.Model):

    class Meta:
        permissions = (
            ('permissao_gerente', 'permissao gerente'),
            ('permissao_supervisor', 'permissao supervisor'),
            ('permissao_vendedor', 'permissao vendedor'),
            ('permissao_funcionario', 'permissao todos funcionarios'),
        )
    situacaoChoices = (
        ('P', 'processada'),
        ('C', 'cancelada'),
        ('F', 'finalizada'),
    )

    formaPagamentoChoices = (
        ('e','especie'),
        ('t','transferencia bancaria'),
        ('c','consorcio'),
    )

    dataHora = models.DateTimeField()
    detalhes = models.CharField(max_length=50)
    valorVenda = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Valor')
    formaPagamento = models.CharField(max_length=1, choices=formaPagamentoChoices, verbose_name='Pagamento')
    cliente = models.ForeignKey(Cliente, on_delete=models.DO_NOTHING)
    colaborador = models.ForeignKey(Colaborador, on_delete=models.DO_NOTHING)
    versao = models.ForeignKey(Versao, on_delete=models.DO_NOTHING)
    situacao = models.CharField(max_length=1, choices=situacaoChoices)    

    def __str__(self) -> str:
        return self.detalhes

vendas/forms.py
from django import forms
from .models import Venda

class VendasModelForm(forms.ModelForm):

    class Meta:
        model = Venda
        fields = '__all__'
        widgets = {'dataHora':forms.DateTimeInput(attrs={'type':'datetime-local'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})
            self.fields[field].widget.attrs.update({'placeholder':field})

vendas/views.py
from django.urls import reverse_lazy
from .models import Venda
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import VendasModelForm
from permissoes.redirecionar import RedirectPermissionRequiredMixin


class VendasListar(RedirectPermissionRequiredMixin, ListView):
    model = Venda
    template_name = 'vendas/vendas.html'
    permission_required = 'vendas.permissao_funcionario'
    paginate_by = 10

class VendasCriar(RedirectPermissionRequiredMixin, CreateView):
    model = Venda
    form_class = VendasModelForm
    template_name = 'vendas/vendaForm.html'
    permission_required = 'vendas.permissao_funcionario'
    success_url = reverse_lazy('vendas:listar')

    def form_valid(self, form):
        versao = form.cleaned_data['versao']
        if versao.estoque <= 0:
            form.add_error('versao', f'{versao.nome} sem estoque!')
            return self.form_invalid(form)
        else:
            messages.success(self.request, 'venda realizada com sucesso. ')
            versao.estoque -= 1
            versao.save()
            return super().form_valid(form)

class VendasEditar(RedirectPermissionRequiredMixin, UpdateView):
    model = Venda
    form_class = VendasModelForm
    template_name = 'vendas/vendaForm.html'
    permission_required = 'vendas.permissao_funcionario'
    success_url = reverse_lazy('vendas:listar')

    def form_valid(self, form):
        versaoAposEditar = form.cleaned_data['versao']
        versaoAntesEditar = self.versaoAntesEditar
        if (versaoAposEditar != versaoAntesEditar):
            if versaoAposEditar.estoque <=0:
                form.add_error('versao', f'{versaoAposEditar.nome} sem estoque!')
                return self.form_invalid(form)
            versaoAntesEditar.estoque += 1
            versaoAposEditar.estoque -= 1
            versaoAposEditar.save()
            versaoAntesEditar.save()
        messages.success(self.request, 'venda editada com sucesso. ')
        return super().form_valid(form)
    
    def get_initial(self):
        initial = super().get_initial()
        object_ = self.get_object()
        initial['dataHora'] = object_.dataHora.strftime('%Y-%m-%dT%H:%M')
        self.versaoAntesEditar = object_.versao
        return initial

class VendasExcluir(RedirectPermissionRequiredMixin, DeleteView):
    model = Venda
    template_name = 'vendas/vendaExcluir.html'
    permission_required = 'vendas.permissao_supervisor'
    success_url = reverse_lazy('vendas:listar')

    def form_valid(self, form):
        messages.success(self.request, 'venda excluida com sucesso. ')
        object_ = self.get_object()
        versao = object_.versao
        versao.estoque += 1
        versao.save()
        return super().form_valid(form)

vendas/templates/vendas/vendaExcluir.html
{% extends 'base.html' %}

{% block 'body' %}
    <h3>Confirma a exclusão desta venda?</h3>
    <ul>
        <li>{{object.dataHora|date:"d/m/Y H:i"}}</li>
        <li>Carro: {{object.versao.carro}}</li>
        <li>Versao: {{object.versao}}</li>
        <li>cliente: {{object.cliente}}</li>
        <li>Valor venda: {{object.valorvenda}}</li>
    </ul>
    <form action="" method="POST"> {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Excluir">
        <a href="javascript:history.back()" class="btn btn-secondary">Voltar</a>
    </form>
{% endblock %}

vendas/templates/vendas/vendaForm.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <form action="" method="POST">{% csrf_token %}
                    <div class="colunasDuas">
                        {% for field in form %}
                                {{ field.label_tag }}
                                {{ field }}
                        {% endfor %}
                    </div>
                    <input type="submit" class="btn btn-success botao" value="Salvar">
                </form>
            </div>
            {% if form.errors %}
                <div class="col-md-3 alert-danger">
                    {{ form.errors}}
                </div>
            {% endif %}
        </div>

    </div>
{% endblock 'body' %}

vendas/templates/vendas/vendas.html
{% extends 'base.html' %}

{% block pagination %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'vendas:criar' %}" class=" btn btn-primary botao">Nova venda</a>
            </div>
            <div class="col-md-5.5">
                {{ block.super }}
            </div>
        </div>
    </div>
{% endblock %}

{% block 'body' %}
    {{ block.super }}
    <div class="container">
        <div class="row">
            <div class="col-md">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th scope="col">Opcoes</th>
                            <th scope="col">Data e hora</th>
                            <th scope="col">Detalhes</th>
                            <th scope="col">valor venda</th>
                            <th scope="col">forma Pag.</th>
                            <th scope="col">Cliente</th>
                            <th scope="col">Colaborador</th>
                            <th scope="col">Carro</th>
                            <th scope="col">Versao</th>
                            <th scope="col">Situacao</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for venda in venda_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'vendas:editar' venda.pk %}" class="btn btn-primary botao_tabela">editar</a>
                                    <a href="{% url 'vendas:excluir' venda.pk %}" class="btn btn-danger botao_tabela">excluir</a>
                                </td>
                                <td>{{venda.dataHora|date:"d/m/Y H:i"}}</td>
                                <td>{{venda.detalhes}}</td>
                                <td>{{venda.valorVenda}}</td>
                                <td>{{venda.get_formaPagamento_display}}</td>
                                <td>{{venda.cliente}}</td>
                                <td>{{venda.colaborador}}</td>
                                <td>{{venda.versao.carro}}</td>
                                <td>{{venda.versao}}</td>
                                <td>{{venda.get_situacao_display}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

{% endblock %}