carros/urls.py
from django.urls import path
from . import views

app_name='carros'
urlpatterns = [
    path('', views.carros, name='listar'),
    path('cadastrar/', views.carroCriar, name='criar'),
    path('editar/<slug:slugCarro>/', views.CarroEditar.as_view(), name='editar'),
    path('excluir/<slug:slugCarro>/', views.CarroExcluir.as_view(), name='excluir'),
]

urlpatterns += [
    path('<slug:slugCarro>/versao/cadastrar/',views.versaoCriar, name='versaoCriar'),
    path('<slug:slugCarro>', views.versoes, name='versoes'),
    path('<slug:slugCarro>/versao/<int:pk>/detalhe', views.VersaoDetalheView.as_view(), name='versaoDetalhe'),
    path('<slug:slugCarro>/versao/<int:pk>/editar', views.VersaoEditar.as_view(), name='versaoEditar'),
    path('<slug:slugCarro>/versao/<int:pk>/excluir', views.VersaoExcluir.as_view(), name='versaoExcluir'),
]

compras/urls.py
from django.urls import path
from . import views


app_name = 'compras'
urlpatterns = [
    path('', views.ComprasListar.as_view(), name='listar'),
    path('cadastrar/', views.CompraCriar.as_view(), name='criar'),
    path('<int:pk>/editar', views.CompraEditar.as_view(), name='editar'),
    path('<int:pk>/excluir', views.CompraExcluirLogica.as_view(), name='excluir'),
]

django_concessionaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='inicio'),
    path('pessoas/', include('pessoas.urls')),
    path('carros/', include('carros.urls')),
    path('clientes/', include('clientes.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
]

urlpatterns += [
    path('contas/', include('django.contrib.auth.urls')),
    path('contas/login/', views.LoginView.as_view(), name='login'),
    path('contas/logout/', views.LogoutView.as_view(), name='logout'),
    path('contas/senha_redefinir/', views.PasswordResetView.as_view(), name='password_reset'),
    path('contas/senha_redifinir/solicitado', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('contas/redefinir/uidb64/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('contas/redefinir/sucesso', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'permissoes.redirecionar.handler403'

compras/models.py
from django.db import models
from carros.models import Versao

class Compra(models.Model):

    class Meta:
        permissions = (
            ('permissao_gerente', 'permissao gerente'),
            ('permissao_supervisor', 'permissao supervisor'),
            ('permissao_vendedor', 'permissao vendedor'),
            ('permissao_funcionario', 'permissao todos funcionarios'),
        )
    dataHora = models.DateTimeField()
    versao = models.ForeignKey(Versao, on_delete=models.DO_NOTHING)
    quantidade = models.IntegerField()
    valorTotal = models.FloatField()

    def __str__(self):
        return (f'{self.versao} - {self.dataHora}')

compras/forms.py
from compras.models import Compra
from django import forms

class ComprasModelForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = '__all__'
        widgets = {'dataHora':forms.DateTimeInput(attrs={'type':'datetime-local'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})
            self.fields[field].widget.attrs.update({'placeholder':field})

compras/views.py
from django.shortcuts import render, redirect
from carros.models import Carro, Versao
from .models import Compra
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from .forms import ComprasModelForm
from permissoes.redirecionar import RedirectPermissionRequiredMixin


class ComprasListar(RedirectPermissionRequiredMixin, ListView):
    model = Compra
    template_name = 'compras/compras.html'
    permission_required = 'compras.permissao_supervisor'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['versoes'] = Versao.objects.all().order_by('-estoque')
        return context

class CompraCriar(RedirectPermissionRequiredMixin, CreateView):
    model = Compra
    form_class = ComprasModelForm
    template_name = 'compras/compraForm.html'
    success_url = reverse_lazy('compras:listar')
    permission_required = 'compras.permissao_supervisor'

    def form_valid(self, form):
        messages.success(self.request, 'compra lancada com sucesso. ')
        versaoCompra = form.cleaned_data.get('versao')
        quantidade = form.cleaned_data.get('quantidade')
        versao = Versao.objects.get(id=versaoCompra.id)
        versao.estoque += quantidade
        versao.save()
        return super().form_valid(form)

class CompraEditar(RedirectPermissionRequiredMixin, UpdateView):
    model = Compra
    form_class = ComprasModelForm
    template_name = 'compras/compraForm.html'
    permission_required = 'compras.permissao_supervisor'
    success_url = reverse_lazy('compras:listar')

    def form_valid(self, form):
        messages.success(self.request, 'compra alterada com sucesso.')
        quantidadeAposEditar = form.cleaned_data['quantidade']
        versaoAposEditar = form.cleaned_data['versao']
        quantidadeAntesEditar = self.quantidadeAntesEditar
        versaoAntesEditar = self.versaoAntesEditar

        if versaoAntesEditar == versaoAposEditar:
            versaoAntesEditar.estoque += quantidadeAposEditar - quantidadeAntesEditar
            versaoAntesEditar.save()
        else:
            versaoAntesEditar.estoque -= quantidadeAntesEditar
            versaoAposEditar.estoque += quantidadeAposEditar
            versaoAposEditar.save()
            versaoAntesEditar.save()
        
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        objeto = self.get_object()
        initial['dataHora'] = objeto.dataHora.strftime('%Y-%m-%dT%H:%M')
        self.versaoAntesEditar = objeto.versao
        self.quantidadeAntesEditar = objeto.quantidade
        return initial

class CompraExcluirLogica(RedirectPermissionRequiredMixin, DeleteView):
    model = Compra
    template_name = 'compras/compraExcluir.html'
    permission_required = 'clientes.permissao_gerente'
    success_url = reverse_lazy('compras:listar')

    def form_valid(self, form):
        messages.success(self.request, 'compra excluida com sucesso.')
        compra = self.get_object()
        versao = Versao.objects.get(id=compra.versao.id)
        quantidade = compra.quantidade
        versao.estoque -= quantidade
        versao.save()
        return super().form_valid(form)

compras/templates/compras/compraExcluir.html
{% extends 'base.html' %}

{% block 'body' %}
    <h3>Confirma a exclusão desta compra?</h3>
    <ul>
        <li>{{object.dataHora|date:"d/m/Y H:i"}}</li>
        <li>{{object.versao.carro}}</li>
        <li>{{object.versao}}</li>
        <li>{{object.quantidade}}</li>
        <li>{{object.valorTotal}}</li>
    </ul>
    <form action="" method="POST"> {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Excluir">
        <a href="javascript:history.back()" class="btn btn-secondary">Voltar</a>
    </form>
{% endblock %}

compras/templates/compras/compraForm.html
{% extends 'base.html' %}

{% block 'body' %}

    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <form action="" method="POST">{% csrf_token %}
                    <div class="colunasDuas">
                        {{form.as_p}}
                    </div>
                    <input class="btn btn-success" type="submit" value="Salvar" >
                    <a href="javascript:history.back()" class="btn btn-secondary botao">Voltar</a>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

compras/templates/compras/compras.html
{% extends 'base.html' %}

{% block pagination %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'compras:criar' %}" class=" btn btn-primary botao">Nova compra</a>
            </div>
            <div class="col-md-5.5">
                {{ block.super }}
            </div>
        </div>
    </div>
{% endblock %}

{% block 'body' %}
    {{ block.super }}
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <table class="table table-dark">
                    <thead>
                        <tr class="headLista">
                            <th scope="col">Opcoes</th>
                            <th scope="col">Data e hora</th>
                            <th scope="col">Carro</th>
                            <th scope="col">Versão</th>
                            <th scope="col">Quant.</th>
                            <th scope="col">Valor Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for compra in compra_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'compras:editar' compra.pk %}" class="btn btn-primary botao_tabela">editar</a>
                                    <a href="{% url 'compras:excluir' compra.pk %}" class="btn btn-danger botao_tabela">excluir</a>
                                </td>
                                <td>{{compra.dataHora|date:"d/m/Y H:i"}}</td>
                                <td>{{compra.versao.carro}}</td>
                                <td>{{compra.versao}}</td>
                                <td>{{compra.quantidade}}</td>
                                <td>{{compra.valorTotal}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    
                </table>
            </div>
            <div class="col-md-4">
                <table class="table table-dark">
                    <thead>
                        <tr class="headLista">
                            <th scope="col">Versao</th>
                            <th scope="col">Estoque</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for versao in versoes %}
                            <tr>
                                <td>{{versao.nome}}</td>
                                <td>{{versao.estoque}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

{% endblock %}