carros/urls.py
from django.urls import path
from . import views

app_name='carros'
urlpatterns = [
    path('', views.carros, name='listar'),
    path('cadastrar/', views.carroCriar, name='criar'),
    path('editar/<slug:slugCarro>/', views.CarroEditar.as_view(), name='editar'),
    path('excluir/<slug:slugCarro>/', views.CarroExcluir.as_view(), name='excluir'),
]

urlpatterns += [
    path('<slug:slugCarro>/versao/cadastrar/',views.versaoCriar, name='versaoCriar'),
    path('<slug:slugCarro>', views.versoes, name='versoes'),
    path('<slug:slugCarro>/versao/<int:pk>/detalhe', views.VersaoDetalheView.as_view(), name='versaoDetalhe'),
    path('<slug:slugCarro>/versao/<int:pk>/editar', views.VersaoEditar.as_view(), name='versaoEditar'),
    path('<slug:slugCarro>/versao/<int:pk>/excluir', views.VersaoExcluir.as_view(), name='versaoExcluir'),
]

clientes/urls.py
from django.urls import path
from . import views


app_name = 'clientes'
urlpatterns = [
    path('', views.ClienteListar.as_view(), name='listar'),
    path('cadastrar/', views.ClienteCriar.as_view(), name='criar'),
    path('editar/<int:pk>', views.ClienteEditar.as_view(), name='editar'),
    path('excluir/<int:pk>', views.ClienteExcluir.as_view(), name='excluir'),
    path('<int:pk>/detalhe', views.ClienteDetalhe.as_view(), name='detalhe'),
]

colaboradores/urls.py
from django.urls import path
from . import views



app_name = 'colaboradores'
urlpatterns = [
    path('', views.ColaboradoresListar.as_view(), name='listar'),
    path('cadastrar/', views.ColaboradorCriar.as_view(), name='criar'),
    path('<int:pk>/detalhe', views.ColaboradorDetalhe.as_view(), name='detalhe'),
    path('<int:pk>/editar', views.ColaboradorEditar.as_view(), name='editar'),
    path('<int:id>/inativar', views.ColaboradorInativar, name='inativar'),
    path('<int:id>/reativar', views.ColaboradorReativar, name='reativar'),
]

compras/urls.py
from django.urls import path
from . import views


app_name = 'compras'
urlpatterns = [
    path('', views.ComprasListar.as_view(), name='listar'),
    path('cadastrar/', views.CompraCriar.as_view(), name='criar'),
    path('<int:pk>/editar', views.CompraEditar.as_view(), name='editar'),
    path('<int:pk>/excluir', views.CompraExcluirLogica.as_view(), name='excluir'),
]

django_concessionaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='inicio'),
    path('pessoas/', include('pessoas.urls')),
    path('carros/', include('carros.urls')),
    path('clientes/', include('clientes.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
]

urlpatterns += [
    path('contas/', include('django.contrib.auth.urls')),
    path('contas/login/', views.LoginView.as_view(), name='login'),
    path('contas/logout/', views.LogoutView.as_view(), name='logout'),
    path('contas/senha_redefinir/', views.PasswordResetView.as_view(), name='password_reset'),
    path('contas/senha_redifinir/solicitado', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('contas/redefinir/uidb64/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('contas/redefinir/sucesso', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'permissoes.redirecionar.handler403'

vendas/urls.py
from django.urls import path
from . import views


app_name = 'vendas'
urlpatterns = [
    path('', views.VendasListar.as_view(), name='listar'),
    path('cadastrar/', views.VendasCriar.as_view(), name='criar'),
    path('editar/<int:pk>', views.VendasEditar.as_view(), name='editar'),
    path('excluir/<int:pk>', views.VendasExcluir.as_view(), name='excluir'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'css/css.css' %}">
    
    {% block 'head' %}
    {% endblock %}

    <title>{% block 'title'%} {% endblock %}</title>
  </head>
  <body class="fundo">
    <nav class="navbar navbar-expand-lg navbar-dark bg-nav">
      <a class="navbar-brand" href="/">Início</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'carros:listar' %}">Carros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=" {% url 'compras:listar' %}">Compras<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=" {% url 'vendas:listar' %}">Vendas <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'clientes:listar' %}">Clientes</span></a>
          </li>          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'colaboradores:listar' %}">Colaboradores</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}" style="color:white">Usuário: {{ user.get_username }} | Sair</a>
            {% else %}
              <a class="nav-link" href="{% url 'login' %}" style="color:white">Entrar</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
   
    {% block pagination %}
      {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  <a href="{{ request.path }}?page={{ page_obj.first }}">Primeira |</a>
                  {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Voltar</a>
                  {% else %}
                    <label class="esmaecido">Voltar</label>
                  {% endif %}
                  <span class="page-current paginacao_pag">
                      | Pag {{ page_obj.number }} de {{ page_obj.paginator.num_pages }} | 
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Proxima</a>
                      {% else %}
                      <label class="esmaecido">Proxima</label>                      
                  {% endif %}
                  <a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">| Ultima</a>
              </span>
          </div>
      {% endif %}
    {% endblock %}
    {% block 'body' %}
      {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block 'body' %}
    {{ block.super }}
    <div class="container">
        <div class="row">
            <div class="col-md-5" style="text-align: justify;">
                <h4 style="text-align: center;">PROJETO FICTÍCIO - CONCESSIONÁRIA</h4>
                <h5>    Simulação de um sistema interno para uso de vendedores, supervisores e gerentes. o cliente não teria acesso.</h5>
            </div>
            <div class="col-md-2">
            </div>
            <div class="col-md-4">
                <table class="table table-dark">
                    <thead>
                        <tr class="headLista">
                            <th scope="col">usuário para testes</th>
                            <th scope="col">senha</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>admin(superuser)</td>
                            <td>8000/admin</td>
                        </tr>
                        <tr>
                            <td>gerente1</td>
                            <td>8000/admin</td>
                        </tr>
                        <tr>
                            <td>supervisor1</td>
                            <td>8000/admin</td>
                        </tr>
                        <tr>
                            <td>vendedor1</td>
                            <td>8000/admin</td>
                        </tr>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>
{% endblock %}